# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gautham/Documents/Projects/LargeScaleMapping

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gautham/Documents/Projects/LargeScaleMapping

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gautham/Documents/Projects/LargeScaleMapping/CMakeFiles /home/gautham/Documents/Projects/LargeScaleMapping//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gautham/Documents/Projects/LargeScaleMapping/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BoWtest

# Build rule for target.
BoWtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BoWtest
.PHONY : BoWtest

# fast build rule for target.
BoWtest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoWtest.dir/build.make CMakeFiles/BoWtest.dir/build
.PHONY : BoWtest/fast

#=============================================================================
# Target rules for targets named visualOdometry

# Build rule for target.
visualOdometry: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 visualOdometry
.PHONY : visualOdometry

# fast build rule for target.
visualOdometry/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualOdometry.dir/build.make CMakeFiles/visualOdometry.dir/build
.PHONY : visualOdometry/fast

#=============================================================================
# Target rules for targets named bundleAdjust

# Build rule for target.
bundleAdjust: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bundleAdjust
.PHONY : bundleAdjust

# fast build rule for target.
bundleAdjust/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bundleAdjust.dir/build.make CMakeFiles/bundleAdjust.dir/build
.PHONY : bundleAdjust/fast

visualOdometry/VisualOdometry.o: visualOdometry/VisualOdometry.cpp.o

.PHONY : visualOdometry/VisualOdometry.o

# target to build an object file
visualOdometry/VisualOdometry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualOdometry.dir/build.make CMakeFiles/visualOdometry.dir/visualOdometry/VisualOdometry.cpp.o
.PHONY : visualOdometry/VisualOdometry.cpp.o

visualOdometry/VisualOdometry.i: visualOdometry/VisualOdometry.cpp.i

.PHONY : visualOdometry/VisualOdometry.i

# target to preprocess a source file
visualOdometry/VisualOdometry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualOdometry.dir/build.make CMakeFiles/visualOdometry.dir/visualOdometry/VisualOdometry.cpp.i
.PHONY : visualOdometry/VisualOdometry.cpp.i

visualOdometry/VisualOdometry.s: visualOdometry/VisualOdometry.cpp.s

.PHONY : visualOdometry/VisualOdometry.s

# target to generate assembly for a file
visualOdometry/VisualOdometry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/visualOdometry.dir/build.make CMakeFiles/visualOdometry.dir/visualOdometry/VisualOdometry.cpp.s
.PHONY : visualOdometry/VisualOdometry.cpp.s

visualOdometry/bagOfWordsDetector.o: visualOdometry/bagOfWordsDetector.cpp.o

.PHONY : visualOdometry/bagOfWordsDetector.o

# target to build an object file
visualOdometry/bagOfWordsDetector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoWtest.dir/build.make CMakeFiles/BoWtest.dir/visualOdometry/bagOfWordsDetector.cpp.o
.PHONY : visualOdometry/bagOfWordsDetector.cpp.o

visualOdometry/bagOfWordsDetector.i: visualOdometry/bagOfWordsDetector.cpp.i

.PHONY : visualOdometry/bagOfWordsDetector.i

# target to preprocess a source file
visualOdometry/bagOfWordsDetector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoWtest.dir/build.make CMakeFiles/BoWtest.dir/visualOdometry/bagOfWordsDetector.cpp.i
.PHONY : visualOdometry/bagOfWordsDetector.cpp.i

visualOdometry/bagOfWordsDetector.s: visualOdometry/bagOfWordsDetector.cpp.s

.PHONY : visualOdometry/bagOfWordsDetector.s

# target to generate assembly for a file
visualOdometry/bagOfWordsDetector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BoWtest.dir/build.make CMakeFiles/BoWtest.dir/visualOdometry/bagOfWordsDetector.cpp.s
.PHONY : visualOdometry/bagOfWordsDetector.cpp.s

visualOdometry/bundleAdjust.o: visualOdometry/bundleAdjust.cpp.o

.PHONY : visualOdometry/bundleAdjust.o

# target to build an object file
visualOdometry/bundleAdjust.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bundleAdjust.dir/build.make CMakeFiles/bundleAdjust.dir/visualOdometry/bundleAdjust.cpp.o
.PHONY : visualOdometry/bundleAdjust.cpp.o

visualOdometry/bundleAdjust.i: visualOdometry/bundleAdjust.cpp.i

.PHONY : visualOdometry/bundleAdjust.i

# target to preprocess a source file
visualOdometry/bundleAdjust.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bundleAdjust.dir/build.make CMakeFiles/bundleAdjust.dir/visualOdometry/bundleAdjust.cpp.i
.PHONY : visualOdometry/bundleAdjust.cpp.i

visualOdometry/bundleAdjust.s: visualOdometry/bundleAdjust.cpp.s

.PHONY : visualOdometry/bundleAdjust.s

# target to generate assembly for a file
visualOdometry/bundleAdjust.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bundleAdjust.dir/build.make CMakeFiles/bundleAdjust.dir/visualOdometry/bundleAdjust.cpp.s
.PHONY : visualOdometry/bundleAdjust.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BoWtest"
	@echo "... bundleAdjust"
	@echo "... visualOdometry"
	@echo "... visualOdometry/VisualOdometry.o"
	@echo "... visualOdometry/VisualOdometry.i"
	@echo "... visualOdometry/VisualOdometry.s"
	@echo "... visualOdometry/bagOfWordsDetector.o"
	@echo "... visualOdometry/bagOfWordsDetector.i"
	@echo "... visualOdometry/bagOfWordsDetector.s"
	@echo "... visualOdometry/bundleAdjust.o"
	@echo "... visualOdometry/bundleAdjust.i"
	@echo "... visualOdometry/bundleAdjust.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

